version: '3'
services:
  db:
    image: mysql:8.0.31
    container_name: authsaur-mysql
    network_mode: host
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}  # Requested, set the root's password of MySQL service.
      - MYSQL_LOG_CONSOLE=true
      - TIMEZONE=Asia/Shanghai
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - ${CURRENT}/mysql/log:/var/log/mysql
      - ${CURRENT}/mysql/data:/var/lib/mysql
      - ${CURRENT}/mysql/conf/my.cnf:/etc/my.cnf
      - ${CURRENT}/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_0900_ai_ci
      --explicit_defaults_for_timestamp=true
      --skip-character-set-client-handshake
      --init-file=/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:5.0.3
    container_name: authsaur-redis
    network_mode: host
    volumes:
      - ${CURRENT}/redis/data:/data
      - ${CURRENT}/redis/logs:/logs
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}

  admin:
    image: deepoove/authsaur-admin-api:1.0.0-beta
    container_name: authsaur-admin-api
    network_mode: host
    volumes:
      - ${CURRENT}/admin/application.properties:/app/resources/application.properties
    # entrypoint: java -Xmx2g -cp @/app/jib-classpath-file com.deepoove.authsaur.AuthsaurAdminApiApplication
    depends_on:
      - db
      - redis

  server:
    image: deepoove/authsaur:1.0.0-beta
    container_name: authsaur-server
    network_mode: host
    volumes:
      - ${CURRENT}/server:/etc/cas/config
    # entrypoint: java -server -noverify -Xmx2048M -XX:+HeapDumpOnOutOfMemoryError -jar cas.war
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:1.18.0
    container_name: authsaur-nginx
    restart: always
    network_mode: host
    volumes:
      - ${CURRENT}/cert:/opt/authsaur/cert
      - ${CURRENT}/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${CURRENT}/nginx/www:/home/www
      - ${CURRENT}/nginx/log:/var/log/nginx
      - ${CURRENT}/nginx/conf.d:/etc/nginx/conf.d
      - ${CURRENT}/nginx/html:/usr/share/nginx/html
      - ${CURRENT}/dashboard:/opt/authsaur/dashboard